//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public bool Type { get; set; }
        public int Health { get; set; }
        public int Magic { get; set; }
        public int Money { get; set; }
        public int Experience { get; set; }
        public int FK_Character_Level { get; set; }
        public int FK_Character_Location { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
