//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public Nullable<int> FK_Inventory_Character { get; set; }
        public Nullable<int> FK_Inventory_Store { get; set; }
        public Nullable<int> FK_Inventory_Armor { get; set; }
        public Nullable<int> FK_Inventory_ArmorEnchantment { get; set; }
        public Nullable<bool> ArmorEquipped { get; set; }
        public Nullable<int> FK_Inventory_Weapon { get; set; }
        public Nullable<int> FK_Inventory_WeaponEnchantment { get; set; }
        public Nullable<bool> WeaponEquipped { get; set; }
        public Nullable<int> FK_Inventory_Spell { get; set; }
        public bool IsPotion { get; set; }
        public int Quantity { get; set; }
    
        public virtual Armor Armor { get; set; }
        public virtual ArmorEnchantment ArmorEnchantment { get; set; }
        public virtual Character Character { get; set; }
        public virtual Weapon Weapon { get; set; }
        public virtual WeaponEnchantment WeaponEnchantment { get; set; }
        public virtual Spell Spell { get; set; }
        public virtual Store Store { get; set; }
    }
}
