//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spell()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int SpellId { get; set; }
        public string Name { get; set; }
        public string Effect { get; set; }
        public int MagicCost { get; set; }
        public int Level { get; set; }
        public string Type { get; set; }
        public int Cost { get; set; }
        public string Description { get; set; }
        public decimal PotionPriceModifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
