//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGameApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextGameEntities : DbContext
    {
        public TextGameEntities()
            : base("name=TextGameEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<ArmorEnchantment> ArmorEnchantments { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
        public virtual DbSet<WeaponEnchantment> WeaponEnchantments { get; set; }
    }
}
